### ISSUE TITLE
golang/mock is no longer maintained

### ISSUE THREAD

**Issue by suntong** [solrac97gr/go-jwt-auth#2]
https://github.com/solrac97gr/go-jwt-auth/blob/f52fb4aa4bb191850660c83132d3926bd86c7dad/README.md?plain=1#L23

golang/mock is _no longer maintained_ -- https://github.com/golang/mock/

Maybe it is time to update the template using the [maintained fork](https://github.com/uber/mock) instead?

BTW, landed here from your [helpful blog](https://cgarciarosales97.medium.com/my-template-for-projects-in-2023-using-go-fiber-and-mongodb-7081341fc9fb). Thanks a lot for _all_ your helpful blogs.

**Comment by solrac97gr** [comment]
Good Catch! I will update it ⭐️, than you so much. Also if you wanna make the change as a PR I will be glad to accept it.

**Comment by suntong** [comment]
Not at the current stage, I cannot even get the old-and-stable golang/mock work for me at the moment (as it seems to require mocking from a go `import`-able path, whereas I was putting the _whole_ project deep under a sub folder, like myproject/demos/go-jwt-auth/testv1, and not within go import path either). So,

Take your time, and thanks again for all your blogs, which is really helpful to me, and I really like the structure you setup to put everything in place, as well as all the components you've put into this template so that we can have a working system to start with.

**Comment by solrac97gr** [comment]
Already updated the principal branch. 👍🏽
